apiVersion: v1
kind: Pod
metadata:
  labels:
    app: postgres
  name: postgres
spec:
  containers:
  - name: postgres
    image: postgres:11.7
    ports:
      - containerPort: 5432
    envFrom:
      - configMapRef:
          name: postgres-config
