apiVersion: v1
kind: Deployment
metadata:
  name: tomcat
  namespace: staging
spec:
  selector:
    matchLabels:
      app: tomcat
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata: 
      labels:
        app: tomcat
      annotations:
        checksum/deployment: TMP_DEP_CHECKSUM
    spec:
      containers:
      - name: tomcat
        image: tomcat
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 10
        resources:
          limits:
            cpu: 100m
            memory: 400M
          requests:
            cpu: 50m
            memory: 200M
        volumeMounts:
        - name: configs
          mountPath: /app
      volumes:
      - name: configs
        configMap:
          name: vol-config-tomcat
